[build-system]
requires = ["setuptools>=75.6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ci_core"
version = "0.1.0"
description = "Source code for Continuous Integration Phase for SDI"
readme = "README.md"
license = {text = "Apache License 2.0"}  # Adjust as needed
authors = [
  { name = "Arogya Kharel", email = "akharel@kaist.ac.kr" },
  { name = "Juyoung Yang", email = "didwndud3299@kaist.ac.kr" }
]
requires-python = ">=3.10"
dependencies = [
  # your requirements.txt content goes here
]

[project.urls]
Homepage = "https://github.com/open-sdi/ci-cv-cd_framework"

